### PR TITLE
Add support for source_code_management_uri, close_old_findings_product_scope,  do_not_reactivate reimport API args

### PR DESCRIPTION
**Pull request by bbbates-tl**
Add support for the following reimport API args:

- `source_code_management_uri`
- `do_not_reactivate`
- `close_old_findings_product_scope`

### CODE REVIEW

**Comment by StefanFl** [comment]
Hi @bbbates-tl, thank you for your contribution. It has been released with 1.0.11.

**Comment by jdfresser** [comment]
Hello @bbbates-tl, thank you for this contribution,

One question, why did you introduced it only the `source_code_management_uri` in the reimport_scan part, and not in the new_engagement/update_engagement?

**Comment by bbbates-tl** [comment]
@jdfresser Just an oversight? TBH I wasn't even aware that it was a argument for the new_engagement/update_engagement services.

**Comment by jdfresser** [comment]
@bbbates-tl, thank you, I was wondering if you did it on purpose or not.

Just opened a PR adding this: https://github.com/MaibornWolff/dd-import/pull/110

**Pull request merged**
